Add missing socket includes.
This makes the "hilti" target compile. However, I still get an
error when trying to link the executable hiltic-nojit:

  /usr/local/bin/ld: ../hilti/libhilti.a(util.cc.o): undefined reference to symbol 'backtrace_symbols_fd'
  //usr/lib/libexecinfo.so.1: error adding symbols: DSO missing from command line
  clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
  *** Error code 1

Needs further investigation.