update pac-file for binpac++-changes
new exports
priority now is a keyword and I may no longer use it.

still broken at the moment, gives

error: identifier or enumerator value in enumerated type definition already exists